# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'puzzle15.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
global pl1x,pl1y,pl2x,pl2y,pl3x,pl3y,pl4x,pl4y,pl5x,pl5y,pl6x,pl6y,pl7x,pl7y,pl8x,pl8y,pl9x,pl9y,pl10x,pl10y,pl11x,pl11y,pl12x,pl12y,pl13x,pl13y,pl14x,pl14y,pl15x,pl15y,pl16x,pl16y
global flag

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(240, 290)
        MainWindow.setMinimumSize(QtCore.QSize(240, 290))
        MainWindow.setMaximumSize(QtCore.QSize(240, 290))
        MainWindow.setStyleSheet("background-color: rgb(40, 203, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 250, 81, 31))
        self.pushButton.setStyleSheet("background-color: rgb(17, 20, 152);\n"
"color: rgb(116, 248, 255);\n"
"font: 700 9pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.pushButton_1.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_1.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_1.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 0, 60, 60))
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_2.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 0, 60, 60))
        self.pushButton_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_3.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_3.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 0, 60, 60))
        self.pushButton_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_4.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_4.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 60, 60, 60))
        self.pushButton_5.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_5.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_5.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 60, 60, 60))
        self.pushButton_6.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_6.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_6.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 60, 60, 60))
        self.pushButton_7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_7.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 60, 60, 60))
        self.pushButton_8.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_8.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_8.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 120, 60, 60))
        self.pushButton_9.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_9.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_9.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 120, 60, 60))
        self.pushButton_10.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_10.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_10.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 120, 60, 60))
        self.pushButton_11.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_11.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_11.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(180, 120, 60, 60))
        self.pushButton_12.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_12.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_12.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 180, 60, 60))
        self.pushButton_13.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_13.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_13.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(60, 180, 60, 60))
        self.pushButton_14.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_14.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_14.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 180, 60, 60))
        self.pushButton_15.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_15.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_15.setStyleSheet("\n"
"background-color: rgb(38, 14, 171);\n"
"border-radius:10px;\n"
"font: 700 34pt \"Segoe UI\";\n"
"color: rgb(40, 203, 239);\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 180, 60, 60))
        self.pushButton_16.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_16.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_16.setStyleSheet("background-color: rgb(40, 203, 239);\n"
"")
        self.pushButton_16.setText("")
        self.pushButton_16.setFlat(True)
        self.pushButton_16.setObjectName("pushButton_16")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def method_start():
                global tx,ty,flag
                flag=0
                tx=[0,60,120,180]
                ty=[0,60,120,180]
                random.shuffle(tx)
                random.shuffle(ty)
                self.pushButton_1.move(tx[0],ty[0])
                self.pushButton_2.move(tx[0],ty[1])
                self.pushButton_3.move(tx[0],ty[2])
                self.pushButton_4.move(tx[0],ty[3])
                self.pushButton_5.move(tx[1],ty[0])
                self.pushButton_6.move(tx[1],ty[1])
                self.pushButton_7.move(tx[1],ty[2])
                self.pushButton_8.move(tx[1],ty[3])
                self.pushButton_9.move(tx[2],ty[0])
                self.pushButton_10.move(tx[2],ty[1])
                self.pushButton_11.move(tx[2],ty[2])
                self.pushButton_12.move(tx[2],ty[3])
                self.pushButton_13.move(tx[3],ty[0])
                self.pushButton_14.move(tx[3],ty[1])
                self.pushButton_15.move(tx[3],ty[2])
                self.pushButton_16.move(tx[3],ty[3])
                
                global pl1x,pl1y,pl2x,pl2y,pl3x,pl3y,pl4x,pl4y,pl5x,pl5y,pl6x,pl6y,pl7x,pl7y,pl8x,pl8y,pl9x,pl9y,pl10x,pl10y,pl11x,pl11y,pl12x,pl12y,pl13x,pl13y,pl14x,pl14y,pl15x,pl15y,pl16x,pl16y

                pl1x=tx[0]
                pl1y=ty[0]
                pl2x=tx[0]
                pl2y=ty[1]
                pl3x=tx[0]
                pl3y=ty[2]
                pl4x=tx[0]
                pl4y=ty[3]

                pl5x=tx[1]
                pl5y=ty[0]
                pl6x=tx[1]
                pl6y=ty[1]
                pl7x=tx[1]
                pl7y=ty[2]
                pl8x=tx[1]
                pl8y=ty[3]

                pl9x=tx[2]
                pl9y=ty[0]
                pl10x=tx[2]
                pl10y=ty[1]
                pl11x=tx[2]
                pl11y=ty[2]
                pl12x=tx[2]
                pl12y=ty[3]

                pl13x=tx[3]
                pl13y=ty[0]
                pl14x=tx[3]
                pl14y=ty[1]
                pl15x=tx[3]
                pl15y=ty[2]
                pl16x=tx[3]
                pl16y=ty[3]
                if flag==1:
                        flag=0
                        self.pushButton.setStyleSheet("background-color: rgb(17, 20, 152);\n"
"color: rgb(116, 248, 255);\n"
"font: 700 9pt \"Segoe UI\";")



        def method_btn1():
                global pl1x,pl16y,pl1y,pl16x
                if pl1x==pl16x+60 and pl1y==pl16y:    
                        self.pushButton_1.move(pl16x,pl16y)
                        self.pushButton_16.move(pl1x,pl1y)
                        x=pl1x
                        y=pl1y
                        pl1x=pl16x
                        pl1y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                        
                elif  pl1x==pl16x-60 and pl1y==pl16y:
                        self.pushButton_1.move(pl16x,pl16y)
                        self.pushButton_16.move(pl1x,pl1y)
                        x=pl1x
                        y=pl1y
                        pl1x=pl16x
                        pl1y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                        
                elif pl1y==pl16y-60 and pl1x==pl16x:
                        self.pushButton_1.move(pl16x,pl16y)
                        self.pushButton_16.move(pl1x,pl1y)
                        x=pl1x
                        y=pl1y
                        pl1x=pl16x
                        pl1y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl1y==pl16y+60 and pl1x==pl16x :
                        self.pushButton_1.move(pl16x,pl16y)
                        self.pushButton_16.move(pl1x,pl1y)
                        x=pl1x
                        y=pl1y
                        pl1x=pl16x
                        pl1y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                
                        

                


        def method_btn2():
                global pl16x,pl16y,pl2x,pl2y
                if pl2x==pl16x+60 and pl2y==pl16y: 
                        self.pushButton_2.move(pl16x,pl16y)
                        self.pushButton_16.move(pl2x,pl2y)
                        x=pl2x
                        y=pl2y
                        pl2x=pl16x
                        pl2y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl2x==pl16x-60 and pl2y==pl16y:
                        self.pushButton_2.move(pl16x,pl16y)
                        self.pushButton_16.move(pl2x,pl2y)
                        x=pl2x
                        y=pl2y
                        pl2x=pl16x
                        pl2y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl2y==pl16y-60 and pl2x==pl16x:
                        self.pushButton_2.move(pl16x,pl16y)
                        self.pushButton_16.move(pl2x,pl2y)
                        x=pl2x
                        y=pl2y
                        pl2x=pl16x
                        pl2y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl2y==pl16y+60 and pl2x==pl16x:
                        self.pushButton_2.move(pl16x,pl16y)
                        self.pushButton_16.move(pl2x,pl2y)
                        x=pl2x
                        y=pl2y
                        pl2x=pl16x
                        pl2y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                        

        def method_btn3():
                global pl16y,pl16x,pl3x,pl3y
                if pl3x==pl16x+60 and pl3y==pl16y:   
                        self.pushButton_3.move(pl16x,pl16y)
                        self.pushButton_16.move(pl3x,pl3y)
                        x=pl3x
                        y=pl3y
                        pl3x=pl16x
                        pl3y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl3x==pl16x-60 and pl3y==pl16y:
                        self.pushButton_3.move(pl16x,pl16y)
                        self.pushButton_16.move(pl3x,pl3y)
                        x=pl3x
                        y=pl3y
                        pl3x=pl16x
                        pl3y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl3y==pl16y-60 and pl3x==pl16x:
                        self.pushButton_3.move(pl16x,pl16y)
                        self.pushButton_16.move(pl3x,pl3y)
                        x=pl3x
                        y=pl3y
                        pl3x=pl16x
                        pl3y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()
                elif pl3y==pl16y+60 and pl3x==pl16x:
                        self.pushButton_3.move(pl16x,pl16y)
                        self.pushButton_16.move(pl3x,pl3y)
                        x=pl3x
                        y=pl3y
                        pl3x=pl16x
                        pl3y=pl16y
                        pl16x=x
                        pl16y=y
                        method_win()



        def method_btn4():
                global pl4x,pl16x,pl4y,pl16y
                if pl4x==pl16x+60 and pl4y==pl16y:   
                       self.pushButton_4.move(pl16x,pl16y)
                       self.pushButton_16.move(pl4x,pl4y)
                       x=pl4x
                       y=pl4y
                       pl4x=pl16x
                       pl4y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl4x+60==pl16x and pl4y==pl16y:
                       self.pushButton_4.move(pl16x,pl16y)
                       self.pushButton_16.move(pl4x,pl4y)
                       x=pl4x
                       y=pl4y
                       pl4x=pl16x
                       pl4y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl4y==pl16y-60 and pl4x==pl16x:
                       self.pushButton_4.move(pl16x,pl16y)
                       self.pushButton_16.move(pl4x,pl4y)
                       x=pl4x
                       y=pl4y
                       pl4x=pl16x
                       pl4y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl4y==pl16y+60 and pl4x==pl16x:
                       self.pushButton_4.move(pl16x,pl16y)
                       self.pushButton_16.move(pl4x,pl4y)
                       x=pl4x
                       y=pl4y
                       pl4x=pl16x
                       pl4y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn5():
                global pl5x,pl16x,pl5y,pl16y
                if pl5x==pl16x+60 and pl5y==pl16y:   
                       self.pushButton_5.move(pl16x,pl16y)
                       self.pushButton_16.move(pl5x,pl5y)
                       x=pl5x
                       y=pl5y
                       pl5x=pl16x
                       pl5y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl5x+60==pl16x and pl5y==pl16y:
                       self.pushButton_5.move(pl16x,pl16y)
                       self.pushButton_16.move(pl5x,pl5y)
                       x=pl5x
                       y=pl5y
                       pl5x=pl16x
                       pl5y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl5y==pl16y-60 and pl5x==pl16x:
                       self.pushButton_5.move(pl16x,pl16y)
                       self.pushButton_16.move(pl5x,pl5y)
                       x=pl5x
                       y=pl5y
                       pl5x=pl16x
                       pl5y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl5y==pl16y+60 and pl5x==pl16x:
                       self.pushButton_5.move(pl16x,pl16y)
                       self.pushButton_16.move(pl5x,pl5y)
                       x=pl5x
                       y=pl5y
                       pl5x=pl16x
                       pl5y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn6():
                global pl6x,pl16x,pl6y,pl16y
                if pl6x==pl16x+60 and pl6y==pl16y:   
                       self.pushButton_6.move(pl16x,pl16y)
                       self.pushButton_16.move(pl6x,pl6y)
                       x=pl6x
                       y=pl6y
                       pl6x=pl16x
                       pl6y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl6x+60==pl16x and pl6y==pl16y:
                       self.pushButton_6.move(pl16x,pl16y)
                       self.pushButton_16.move(pl6x,pl6y)
                       x=pl6x
                       y=pl6y
                       pl6x=pl16x
                       pl6y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl6y==pl16y-60 and pl6x==pl16x:
                       self.pushButton_6.move(pl16x,pl16y)
                       self.pushButton_16.move(pl6x,pl6y)
                       x=pl6x
                       y=pl6y
                       pl6x=pl16x
                       pl6y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl6y==pl16y+60 and pl6x==pl16x:
                       self.pushButton_6.move(pl16x,pl16y)
                       self.pushButton_16.move(pl6x,pl6y)
                       x=pl6x
                       y=pl6y
                       pl6x=pl16x
                       pl6y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn7():
                global pl7x,pl16x,pl7y,pl16y
                if pl7x==pl16x+60 and pl7y==pl16y:   
                       self.pushButton_7.move(pl16x,pl16y)
                       self.pushButton_16.move(pl7x,pl7y)
                       x=pl7x
                       y=pl7y
                       pl7x=pl16x
                       pl7y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl7x+60==pl16x and pl7y==pl16y:
                       self.pushButton_7.move(pl16x,pl16y)
                       self.pushButton_16.move(pl7x,pl7y)
                       x=pl7x
                       y=pl7y
                       pl7x=pl16x
                       pl7y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl7y==pl16y-60 and pl7x==pl16x:
                       self.pushButton_7.move(pl16x,pl16y)
                       self.pushButton_16.move(pl7x,pl7y)
                       x=pl7x
                       y=pl7y
                       pl7x=pl16x
                       pl7y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl7y==pl16y+60 and pl7x==pl16x:
                       self.pushButton_7.move(pl16x,pl16y)
                       self.pushButton_16.move(pl7x,pl7y)
                       x=pl7x
                       y=pl7y
                       pl7x=pl16x
                       pl7y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn8():
                global pl8x,pl16x,pl8y,pl16y
                if pl8x==pl16x+60 and pl8y==pl16y:   
                       self.pushButton_8.move(pl16x,pl16y)
                       self.pushButton_16.move(pl8x,pl8y)
                       x=pl8x
                       y=pl8y
                       pl8x=pl16x
                       pl8y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl8x+60==pl16x and pl8y==pl16y:
                       self.pushButton_8.move(pl16x,pl16y)
                       self.pushButton_16.move(pl8x,pl8y)
                       x=pl8x
                       y=pl8y
                       pl8x=pl16x
                       pl8y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl8y==pl16y-60 and pl8x==pl16x:
                       self.pushButton_8.move(pl16x,pl16y)
                       self.pushButton_16.move(pl8x,pl8y)
                       x=pl8x
                       y=pl8y
                       pl8x=pl16x
                       pl8y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl8y==pl16y+60 and pl8x==pl16x:
                       self.pushButton_8.move(pl16x,pl16y)
                       self.pushButton_16.move(pl8x,pl8y)
                       x=pl8x
                       y=pl8y
                       pl8x=pl16x
                       pl8y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn9():
                global pl9x,pl16x,pl9y,pl16y
                if pl9x==pl16x+60 and pl9y==pl16y:   
                       self.pushButton_9.move(pl16x,pl16y)
                       self.pushButton_16.move(pl9x,pl9y)
                       x=pl9x
                       y=pl9y
                       pl9x=pl16x
                       pl9y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl9x+60==pl16x and pl9y==pl16y:
                       self.pushButton_9.move(pl16x,pl16y)
                       self.pushButton_16.move(pl9x,pl9y)
                       x=pl9x
                       y=pl9y
                       pl9x=pl16x
                       pl9y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl9y==pl16y-60 and pl9x==pl16x:
                       self.pushButton_9.move(pl16x,pl16y)
                       self.pushButton_16.move(pl9x,pl9y)
                       x=pl9x
                       y=pl9y
                       pl9x=pl16x
                       pl9y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl9y==pl16y+60 and pl9x==pl16x:
                       self.pushButton_9.move(pl16x,pl16y)
                       self.pushButton_16.move(pl9x,pl9y)
                       x=pl9x
                       y=pl9y
                       pl9x=pl16x
                       pl9y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn10():
                global pl10x,pl16x,pl10y,pl16y
                if pl10x==pl16x+60 and pl10y==pl16y:   
                       self.pushButton_10.move(pl16x,pl16y)
                       self.pushButton_16.move(pl10x,pl10y)
                       x=pl10x
                       y=pl10y
                       pl10x=pl16x
                       pl10y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl10x+60==pl16x and pl10y==pl16y:
                       self.pushButton_10.move(pl16x,pl16y)
                       self.pushButton_16.move(pl10x,pl10y)
                       x=pl10x
                       y=pl10y
                       pl10x=pl16x
                       pl10y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl10y==pl16y-60 and pl10x==pl16x:
                       self.pushButton_10.move(pl16x,pl16y)
                       self.pushButton_16.move(pl10x,pl10y)
                       x=pl10x
                       y=pl10y
                       pl10x=pl16x
                       pl10y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl10y==pl16y+60 and pl10x==pl16x:
                       self.pushButton_10.move(pl16x,pl16y)
                       self.pushButton_16.move(pl10x,pl10y)
                       x=pl10x
                       y=pl10y
                       pl10x=pl16x
                       pl10y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn11():
                global pl11x,pl16x,pl11y,pl16y
                if pl11x==pl16x+60 and pl11y==pl16y:   
                       self.pushButton_11.move(pl16x,pl16y)
                       self.pushButton_16.move(pl11x,pl11y)
                       x=pl11x
                       y=pl11y
                       pl11x=pl16x
                       pl11y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl11x+60==pl16x and pl11y==pl16y:
                       self.pushButton_11.move(pl16x,pl16y)
                       self.pushButton_16.move(pl11x,pl11y)
                       x=pl11x
                       y=pl11y
                       pl11x=pl16x
                       pl11y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl11y==pl16y-60 and pl11x==pl16x:
                       self.pushButton_11.move(pl16x,pl16y)
                       self.pushButton_16.move(pl11x,pl11y)
                       x=pl11x
                       y=pl11y
                       pl11x=pl16x
                       pl11y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl11y==pl16y+60 and pl11x==pl16x:
                       self.pushButton_11.move(pl16x,pl16y)
                       self.pushButton_16.move(pl11x,pl11y)
                       x=pl11x
                       y=pl11y
                       pl11x=pl16x
                       pl11y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
        def method_btn12():
                global pl12x,pl16x,pl12y,pl16y
                if pl12x==pl16x+60 and pl12y==pl16y:   
                       self.pushButton_12.move(pl16x,pl16y)
                       self.pushButton_16.move(pl12x,pl12y)
                       x=pl12x
                       y=pl12y
                       pl12x=pl16x
                       pl12y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl12x+60==pl16x and pl12y==pl16y:
                       self.pushButton_12.move(pl16x,pl16y)
                       self.pushButton_16.move(pl12x,pl12y)
                       x=pl12x
                       y=pl12y
                       pl12x=pl16x
                       pl12y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl12y==pl16y-60 and pl12x==pl16x:
                       self.pushButton_12.move(pl16x,pl16y)
                       self.pushButton_16.move(pl12x,pl12y)
                       x=pl12x
                       y=pl12y
                       pl12x=pl16x
                       pl12y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl12y==pl16y+60 and pl12x==pl16x:
                       self.pushButton_12.move(pl16x,pl16y)
                       self.pushButton_16.move(pl12x,pl12y)
                       x=pl12x
                       y=pl12y
                       pl12x=pl16x
                       pl12y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn13():
                global pl13x,pl16x,pl13y,pl16y
                if pl13x==pl16x+60 and pl13y==pl16y:   
                       self.pushButton_13.move(pl16x,pl16y)
                       self.pushButton_16.move(pl13x,pl13y)
                       x=pl13x
                       y=pl13y
                       pl13x=pl16x
                       pl13y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl13x+60==pl16x and pl13y==pl16y:
                       self.pushButton_13.move(pl16x,pl16y)
                       self.pushButton_16.move(pl13x,pl13y)
                       x=pl13x
                       y=pl13y
                       pl13x=pl16x
                       pl13y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl13y==pl16y-60 and pl13x==pl16x:
                       self.pushButton_13.move(pl16x,pl16y)
                       self.pushButton_16.move(pl13x,pl13y)
                       x=pl13x
                       y=pl13y
                       pl13x=pl16x
                       pl13y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl13y==pl16y+60 and pl13x==pl16x:
                       self.pushButton_13.move(pl16x,pl16y)
                       self.pushButton_16.move(pl13x,pl13y)
                       x=pl13x
                       y=pl13y
                       pl13x=pl16x
                       pl13y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn14():
                global pl14x,pl16x,pl14y,pl16y
                if pl14x==pl16x+60 and pl14y==pl16y:   
                       self.pushButton_14.move(pl16x,pl16y)
                       self.pushButton_16.move(pl14x,pl14y)
                       x=pl14x
                       y=pl14y
                       pl14x=pl16x
                       pl14y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl14x+60==pl16x and pl14y==pl16y:
                       self.pushButton_14.move(pl16x,pl16y)
                       self.pushButton_16.move(pl14x,pl14y)
                       x=pl14x
                       y=pl14y
                       pl14x=pl16x
                       pl14y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl14y==pl16y-60 and pl14x==pl16x:
                       self.pushButton_14.move(pl16x,pl16y)
                       self.pushButton_16.move(pl14x,pl14y)
                       x=pl14x
                       y=pl14y
                       pl14x=pl16x
                       pl14y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl14y==pl16y+60 and pl14x==pl16x:
                       self.pushButton_14.move(pl16x,pl16y)
                       self.pushButton_16.move(pl14x,pl14y)
                       x=pl14x
                       y=pl14y
                       pl14x=pl16x
                       pl14y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_btn15():
                global pl15x,pl16x,pl15y,pl16y
                if pl15x==pl16x+60 and pl15y==pl16y:   
                       self.pushButton_15.move(pl16x,pl16y)
                       self.pushButton_16.move(pl15x,pl15y)
                       x=pl15x
                       y=pl15y
                       pl15x=pl16x
                       pl15y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl15x+60==pl16x and pl15y==pl16y:
                       self.pushButton_15.move(pl16x,pl16y)
                       self.pushButton_16.move(pl15x,pl15y)
                       x=pl15x
                       y=pl15y
                       pl15x=pl16x
                       pl15y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl15y==pl16y-60 and pl15x==pl16x:
                       self.pushButton_15.move(pl16x,pl16y)
                       self.pushButton_16.move(pl15x,pl15y)
                       x=pl15x
                       y=pl15y
                       pl15x=pl16x
                       pl15y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()
                elif pl15y==pl16y+60 and pl15x==pl16x:
                       self.pushButton_15.move(pl16x,pl16y)
                       self.pushButton_16.move(pl15x,pl15y)
                       x=pl15x
                       y=pl15y
                       pl15x=pl16x
                       pl15y=pl16y
                       pl16x=x
                       pl16y=y
                       method_win()

        def method_win():
                global flag
                if pl1x==0 and pl1y==0 and pl2x==60 and pl2y==0 and pl3x==120 and pl3y==0 and pl4x==180 and pl4y==0 and pl5x==0 and pl5y==60 and pl6x==60 and pl6y==60 and pl7x==120 and pl7y==60 and pl8x==180 and pl8y==60 and pl9x==0 and pl9y==120 and pl10x==60 and pl10y==120 and pl11x==120 and pl11y==120 and pl12x==180 and pl12y==120 and pl13x==0 and pl13y==180 and pl14x==60 and pl14y==180 and pl15x==120 and pl15y==180 and pl16x==180 and pl16y==180 :
                        self.pushButton.setText("you win")
                        flag=1
                        self.pushButton.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"font: 700 8pt \"Segoe UI\";\n"
"color: rgb(92, 212, 17);\n"
"")

                        



        method_start()
        self.pushButton.clicked.connect(method_start)
        self.pushButton_1.clicked.connect(method_btn1)
        self.pushButton_2.clicked.connect(method_btn2)
        self.pushButton_3.clicked.connect(method_btn3)
        self.pushButton_4.clicked.connect(method_btn4)
        self.pushButton_5.clicked.connect(method_btn5)
        self.pushButton_6.clicked.connect(method_btn6)
        self.pushButton_7.clicked.connect(method_btn7)
        self.pushButton_8.clicked.connect(method_btn8)
        self.pushButton_9.clicked.connect(method_btn9)
        self.pushButton_10.clicked.connect(method_btn10)
        self.pushButton_11.clicked.connect(method_btn11)
        self.pushButton_12.clicked.connect(method_btn12)
        self.pushButton_13.clicked.connect(method_btn13)
        self.pushButton_14.clicked.connect(method_btn14)
        self.pushButton_15.clicked.connect(method_btn15)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Puzzle 15"))
        self.pushButton.setText(_translate("MainWindow", "Restart"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_10.setText(_translate("MainWindow", "10"))
        self.pushButton_11.setText(_translate("MainWindow", "11"))
        self.pushButton_12.setText(_translate("MainWindow", "12"))
        self.pushButton_13.setText(_translate("MainWindow", "13"))
        self.pushButton_14.setText(_translate("MainWindow", "14"))
        self.pushButton_15.setText(_translate("MainWindow", "15"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
